In [131]:
import numpy as np
import scipy as sc
from math import log as log

my_array = np.random.choice([0,1], size=(10, ))

my_array = np.random.rand(3, 10, 10, 2)

In [132]:
my_array.shape

(3, 10, 10, 2)

In [134]:
for v in range(my_array.shape[0]):
    print(my_array[v, ...])

[[[ 0.57470388  0.0943146 ]
  [ 0.02165066  0.85593826]
  [ 0.86557479  0.01172015]
  [ 0.10590389  0.54733341]
  [ 0.57231065  0.61578376]
  [ 0.71333249  0.64876422]
  [ 0.536436    0.26584642]
  [ 0.44089475  0.77582755]
  [ 0.14218646  0.33665124]
  [ 0.78635144  0.3616916 ]]

 [[ 0.05676949  0.22784851]
  [ 0.44537098  0.24782435]
  [ 0.6796172   0.1737657 ]
  [ 0.82634997  0.4574818 ]
  [ 0.75378824  0.86544772]
  [ 0.9359626   0.5894015 ]
  [ 0.99789812  0.90802485]
  [ 0.40755678  0.02143686]
  [ 0.16145615  0.28692846]
  [ 0.89152031  0.78822655]]

 [[ 0.97838529  0.3941756 ]
  [ 0.37174052  0.28862196]
  [ 0.9798889   0.08732422]
  [ 0.99966343  0.79369994]
  [ 0.88988204  0.2940025 ]
  [ 0.46788804  0.83141593]
  [ 0.27552604  0.30493496]
  [ 0.21725091  0.09989039]
  [ 0.76833043  0.85920164]
  [ 0.49247921  0.29134597]]

 [[ 0.20694548  0.88924978]
  [ 0.16043167  0.79169611]
  [ 0.20067929  0.42719048]
  [ 0.29788559  0.97736173]
  [ 0.41742674  0.87281516]
  [ 0.82566076

In [91]:
def entropy2(labels):
    """ Computes entropy of label distribution. """
    n_labels = len(labels)

    if n_labels <= 1:
        return 0

    counts = np.bincount(labels)
    probs = counts / n_labels
    n_classes = np.count_nonzero(probs)

    if n_classes <= 1:
        return 0

    ent = 0.

    # Compute standard entropy.
    for i in probs:
        ent -= i * log(i, n_classes)

    return ent

In [128]:
my_array = np.random.choice([0,1], size=(10,))
print(my_array)
print(entropy2(my_array))
print(np.std(my_array))

[0 0 0 0 0 1 0 0 1 1]
0.881290899231
0.458257569496


In [136]:
np.argmax(my_array, axis=3).dtype


dtype('int64')

In [1]:
import tensorflow